%%

In [1]:
import numpy as np
from matplotlib import pyplot as plt
'''
Todo esto sale de:
https://realpython.com/np-linspace-numpy/?__s=ys765jm76xn5wmdbddxy
'''

'\nTodo esto sale de:\nhttps://realpython.com/np-linspace-numpy/?__s=ys765jm76xn5wmdbddxy\n'

%%<br>
Serie de números equiespaciados con una cantidad de datos DETERMINADA<br>
Contiene al start y al stop<br>
linspace genera float (a menos que se especifique otra cosa)

In [2]:
ej_1 = np.linspace(start=0, stop=10, num=11)
print(ej_1)
print(type(ej_1))
print(type(ej_1[0]))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


%%<br>
Podemos averiguar la separación entre elementos de linspace

In [3]:
numeros, step = np.linspace(start=0, stop=10, num=20, retstep=True)
print(numeros)
print(step)
# %%
# Serie de números con un ESPACIAMIENTO BIEN DEFINIDO
# arange genera enteros

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
0.5263157894736842


In [18]:
ej_2 = np.arange(start=0, stop=10, step=3)
print(ej_2)
print(type(ej_2))
print(type(ej_2[0]))
# %%
# Cosas un poco más raras
# Armar matrices con valores

[0 3 6 9]
<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [19]:
mat, esp = np.linspace(start=[1, 10, 100], stop=[10, 50, 200], num=10, retstep=True)
print(mat)
print(mat.shape)
print(esp)

[[  1.          10.         100.        ]
 [  2.          14.44444444 111.11111111]
 [  3.          18.88888889 122.22222222]
 [  4.          23.33333333 133.33333333]
 [  5.          27.77777778 144.44444444]
 [  6.          32.22222222 155.55555556]
 [  7.          36.66666667 166.66666667]
 [  8.          41.11111111 177.77777778]
 [  9.          45.55555556 188.88888889]
 [ 10.          50.         200.        ]]
(10, 3)
[ 1.          4.44444444 11.11111111]


%%<br>
Podemos trasponer esto de una

In [21]:
mat_T = np.linspace(start=[1, 10, 100], stop=[10, 50, 200], num=10, axis=1)
print(mat_T)
print(mat_T.shape)
# %%
'''
En resumen, la función linspace tiene esta pinta:'''

[[  1.           2.           3.           4.           5.
    6.           7.           8.           9.          10.        ]
 [ 10.          14.44444444  18.88888889  23.33333333  27.77777778
   32.22222222  36.66666667  41.11111111  45.55555556  50.        ]
 [100.         111.11111111 122.22222222 133.33333333 144.44444444
  155.55555556 166.66666667 177.77777778 188.88888889 200.        ]]
(3, 10)


'\nEn resumen, la función linspace tiene esta pinta:'

In [ ]:
linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [ ]:
num = Cant de valores generados
endpoint = Si es True, incluye el Stop
retstep = Devuelve la longitud entre los valores
dtype = Especifica el tipo de dato
axis = 1 -> Traspone

In [2]:
import numpy as np
# Cosas lindas que se pueden hacer con el linspace
x_ = np.linspace(-5, 5, 100)
y_ = 4 * (x_**3) + 2 * (x_**2) + 5 * x_
plt.plot(x_, y_)

# Parameters for discretizing the mathematical function
sampling = 100
x_range = -10, 10
n_waves = 3
# Parameters are tuples with a value for each wave (2 in this case)
amplitudes = 1.7, 0.8, 5.3
wavelengths = 4, 7.5, 1
velocities = 2, 1.5, 7
time = 0  # You can set time to 0 for now
x_ = np.linspace(x_range[0], x_range[1], sampling)
# Create 2 (or more) waves using a list comprehension and superimpose
waves = [amplitudes[idx] * np.sin((2 * np.pi / wavelengths[idx]) * (x_ - velocities[idx] * time)) for idx in range(n_waves)]
superimposed_wave = sum(waves)
# Plot both waves separately to see what they look like
plt.subplot(2, 1, 1)
plt.plot(x_, waves[0])
plt.plot(x_, waves[1])
plt.plot(x_, waves[2])
# Plot the superimposed wave
plt.subplot(2, 1, 2)
plt.plot(x_, superimposed_wave)
plt.show()

for time in np.arange(0, 40, 0.2):
    # Create 2 (or more) waves using a list comprehension and superimpose
    waves = [amplitudes[idx] *
             np.sin((2 * np.pi / wavelengths[idx]) * (x_ - velocities[idx] * time)) for idx in range(n_waves)]
    superimposed_wave = sum(waves)
    plt.clf()  # Clear last figure
    plt.plot(x_, superimposed_wave)
    plt.ylim(-3, 3)  # Fix the limits on the y-axis
    plt.pause(0.1)  # Insert short pause to create animation

NameError: name 'plt' is not defined